### ISSUE TITLE
[FIX] Fix Title of the Website

### ISSUE THREAD

**Issue by Coding-Hashira** [pushkaraj2007/Threadify#12]
# Problem

Currently, Threadify's title is the default one NextJS gives, which is Create Next App. It should be changed to Threadify.

# Solution

In `pages/index.ts` file, replace the 'Create Next App' in `<title>` tag with 'Threadify'.

**Comment by TanmayBhosale** [comment]
If it's not assigned I can do this!

**Comment by pushkaraj2007** [comment]
Sure @TanmayBhosale, 

Go ahead 🚀

**Comment by TanmayBhosale** [comment]
Can we create a meta component? Where we can pass in other meta tags like description, title so that it becomes a reusable component

**Comment by pushkaraj2007** [comment]
I think we only need to use it in index.tsx file, right? 

If so, I don't think making sperate component is necessary.

**Comment by TanmayBhosale** [comment]
We can have different pages right? home page maybe login and a profile page? So we can name the pages accordingly. Would be a better practice

**Comment by pushkaraj2007** [comment]
@TanmayBhosale 

Yeah, you are right. 

Go with it, happy contributing :)

**Comment by pushkaraj2007** [comment]
Yeah, you are right.

Go with it, happy contributing :)

**Comment by TanmayBhosale** [comment]
On it!
