### ISSUE TITLE
[Bug] Fix background color

### ISSUE THREAD

**Issue by TanmayBhosale** [pushkaraj2007/Threadify#13]
### Bug
- Background color is set to black and hence can't properly view the text

![Screenshot (50)](https://user-images.githubusercontent.com/66182596/195265062-85a950c3-6475-4cde-a16d-6f5b0d20ae04.png)

### Fix
- change the background-color in the global CSS file to white

**Comment by TanmayBhosale** [comment]
would like to work on this!

**Comment by jsvigneshkanna** [comment]
@pushkaraj2007 ,

please assign this to my name

**Comment by pushkaraj2007** [comment]
@TanmayBhosale

It's actually the default code written by nextJS which switch between dark mode according to system settings.

if you can do something to make text color look more white, do it.

**Comment by pushkaraj2007** [comment]
BTW, I'm agree on @Coding-Hashira's point, I was thinking of implementing this feature. 

If you (@TanmayBhosale) want to work on that feature, let me know!

**Comment by Coding-Hashira** [comment]
Actually, I think implementing our own dark mode in the app is the only way to fix this issue. I'm not sure though.

**Comment by Coding-Hashira** [comment]
> And I'm sorry @jsvigneshkanna, but I think Tanmay wants to work on this issue and as he asked first I'm going to assign him.
> 
> You can check out other issues in the issues tab or create one if you want.

Maybe he can work on #15

**Comment by pushkaraj2007** [comment]
Yeah! I think the same too.

Let's see if Tanmay wants to work on this, if so I'll create a separate issue and assign it to him.

**Comment by TanmayBhosale** [comment]
Do you want to implement a light/ dark mode ? I can do that

**Comment by pushkaraj2007** [comment]
You got it right @TanmayBhosale 

Let me just create a new issue for adding this feature, you have to comment on that issue so I can assign it to you.

**Comment by TanmayBhosale** [comment]
up sure will do

**Comment by pushkaraj2007** [comment]
> up sure will do

The issue has been created #16

**Comment by TanmayBhosale** [comment]
Yup! You can close this issue if it's not needed.

**Comment by pushkaraj2007** [comment]
Closing this issue now!
