### ISSUE TITLE
Add a Contributing Guide

### ISSUE THREAD

**Issue by Coding-Hashira** [pushkaraj2007/Threadify#15]
Currently, we don't have any contributing guidelines for this project. It'd be great to add one, as it'll help new contributors understand the project well, and contribute in a better way.

Also, I'm completely fine if someone else wants to work on it! 😉

**Comment by pushkaraj2007** [comment]
Do you want to work on this?

**Comment by pushkaraj2007** [comment]
It's necessary too! 

Let's see if anyone wants to work on this, otherwise you can take this one.

**Comment by kuberaspeaking** [comment]
hi @pushkaraj2007 can you assign this to me?

**Comment by pushkaraj2007** [comment]
Sure, go ahead.

**Comment by pushkaraj2007** [comment]
BTW, which template are you going to follow?

**Comment by kuberaspeaking** [comment]
I made [this one](https://github.com/SSGorg/Cryptex/blob/main/CONTRIBUTING.md) for another project yesterday. Was planning to follow the same template.

**Comment by pushkaraj2007** [comment]
It looks good!

Follow the template, Happy contributing :)

**Comment by pushkaraj2007** [comment]
!! This issue has been resolved !!
