### ISSUE TITLE
[FEAT] Add a button to switch between light mode and dark mode 

### ISSUE THREAD

**Issue by pushkaraj2007** [pushkaraj2007/Threadify#16]
## Description:

It will be a great user experience if we add a button to switch between dark mode and light mode, as some people prefer to use light mode and some dark mode.

We can place the button on the navbar for now.

**Comment by TanmayBhosale** [comment]
Will like to work on it

**Comment by pushkaraj2007** [comment]
Sure, go ahead.

**Comment by pushkaraj2007** [comment]
This issue has been resolved in #18 PR!
