### ISSUE TITLE
[BUG] Change default favicon

### ISSUE THREAD

**Issue by pushkaraj2007** [pushkaraj2007/Threadify#19]
## Problem:

Currently, the application is using the default icon of NextJS, we have to change it to the Threadify logo.

## Solution:

Go to components/Meta.jsx and change the favicon href from `/favicon.ico` to `/threadify-logo.png`

**Comment by stevenovak123** [comment]
Hey can you assign this to me?

**Comment by pushkaraj2007** [comment]
Sure, go ahead.
