### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by Coding-Hashira** [pushkaraj2007/Threadify#2]
Currently, the project is using default README of NextJS, which is definitely not good. It'll be better to add a custom README.

**Comment by pushkaraj2007** [comment]
Great idea!

Any template in mind?

**Comment by Coding-Hashira** [comment]
As of now, no

**Comment by pushkaraj2007** [comment]
What about [Cardit's](https://github.com/pushkaraj2007/Cardit) type of readme?

**Comment by Coding-Hashira** [comment]
> What about [Cardit's](https://github.com/pushkaraj2007/Cardit) type of readme?

Yea, it's good! 🔥⚡

**Comment by pushkaraj2007** [comment]
So should we go with it?

**Comment by Coding-Hashira** [comment]
Yep!

**Comment by Coding-Hashira** [comment]
@pushkaraj2007 are you doing the README?

If not, could you please assign this issue to me?

**Comment by pushkaraj2007** [comment]
Sure @Coding-Hashira 

I'm currently focusing on backend and API part, you can work on this issue. 

Going to assign this to you.

**Comment by pushkaraj2007** [comment]
Hey @Coding-Hashira, are you working on this?

**Comment by Coding-Hashira** [comment]
> Hey @Coding-Hashira, are you working on this? 

Sorry bro, was busy with schools and all! 😅

Will try my best to do it today! 😉

**Comment by pushkaraj2007** [comment]
@Coding-Hashira 

No problem! Take your time... 😊
