### ISSUE TITLE
Create a Layout component

### ISSUE THREAD

**Issue by TanmayBhosale** [pushkaraj2007/Threadify#20]
Currently, we have navbar and footer components in index.tsx, but when we have new routes these components won't be visible.

Ideally, there should be a Layout component that contains the nav and footer components. This Layout component then wraps around < Component  /> from the _app.tsx file.

This will make the navbar and footer available on all the pages.

**Comment by stevenovak123** [comment]
Hey can you assign this to me?

**Comment by pushkaraj2007** [comment]
Looks like a great idea, do you want to work on this, @TanmayBhosale?

**Comment by TanmayBhosale** [comment]
Let @stevenovak123 have it I'll work on something different

**Comment by TanmayBhosale** [comment]
Do we have any backend work I would like to do that

**Comment by pushkaraj2007** [comment]
So @stevenovak123, do you want to work on this?

**Comment by stevenovak123** [comment]
Yeah I can

**Comment by pushkaraj2007** [comment]
@TanmayBhosale 

Currently implementing Twitter login functionality, will inform you once the basic backend gets developed.

**Comment by pushkaraj2007** [comment]
@stevenovak123 

Go ahead, I'm assigning this issue to you.

**Comment by stevenovak123** [comment]
Alright. Thanks !!

**Comment by Coding-Hashira** [comment]
> Yup okay sure! Till then can we make a contributors page? We can just keep a list of contributors and make a page to display it. I think this will encourage contribution.

On website? Something like: "Threadify is possible due to these awesome contributors, become one, too!"

Great idea, actually!!

**Comment by TanmayBhosale** [comment]
Yup! We can have a route /contributors where we can display all the contributors. Should I create a separate issue for this?

**Comment by pushkaraj2007** [comment]
Looks like a great idea @TanmayBhosale.

BTW, how are going to fetch who has contributed?

**Comment by Coding-Hashira** [comment]
I think you should create a separate issue for this.

**Comment by TanmayBhosale** [comment]
Yup

**Comment by pushkaraj2007** [comment]
🎉 This issue has been resolved 🎉
