### ISSUE TITLE
Create a contributors page

### ISSUE THREAD

**Issue by TanmayBhosale** [pushkaraj2007/Threadify#23]
Create a contributor's page and display a list of all the contributors.

**Comment by TanmayBhosale** [comment]
How are we going to go about this? Should we use APIs? or should we just ask contributors to add their details to a JSON file?

**Comment by Coding-Hashira** [comment]
> How are we going to go about this? Should we use APIs? or should we just ask contributors to add their details to a JSON file?

I think API is better. Otherwise, anyone will put his/her name in the JSON file, without actually contributing to the project!

Also, do you have any experience of working with GitHub API?

**Comment by pushkaraj2007** [comment]
I think, using API is more preferable. 

However, I'm open for the discussion. 

What do you think?

**Comment by Coding-Hashira** [comment]
> > > How are we going to go about this? Should we use APIs? or should we just ask contributors to add their details to a JSON file?
> > 
> > I think API is better. Otherwise, anyone will put his/her name in the JSON file, without actually contributing to the project!
> > 
> > Also, do you have any experience of working with GitHub API?
> 
> We can check if he/she is contributor or not, however we'll get many spam PRs if we use the JSON file approach. 

Spam PRs are the problem, and they'll increase with time, only! Using GitHub API can save our time! Also, of we want, we can also show other data related to contributor. (Depends on what GitHub API has to offer)

**Comment by Coding-Hashira** [comment]
> > > How are we going to go about this? Should we use APIs? or should we just ask contributors to add their details to a JSON file?
> > 
> > I think API is better. Otherwise, anyone will put his/her name in the JSON file, without actually contributing to the project!
> > 
> > Also, do you have any experience of working with GitHub API?
> 
> We can check if he/she is contributor or not, however we'll get many spam PRs if we use the JSON file approach. 

Spam PRs are the problem, and they'll increase with time, only! Using GitHub API can save our time! Also, of we want, we can also show other data related to contributor. (Depends on what GitHub API has to offer)

**Comment by Coding-Hashira** [comment]
Apart from that, are there any cons of using GitHub API?

**Comment by pushkaraj2007** [comment]
We have to manage some keys and secrets in a .env file, and it will become hard for contributors to work on that.

I think that is the only downside of using API.

**Comment by Coding-Hashira** [comment]
> We have to manage some keys and secrets in a .env file, and it will become hard for contributors to work on that.
> 
> I think that is the only downside of using API.

For the keys, we're already using 1 API, I don't think there's any problem in using another one.

**Comment by TanmayBhosale** [comment]
I have worked with APIs but not GitHub's api specifically. But can look into it. And about the keys part, as this is just a enhancement and we won't have to work on it in future so it will be optional for contributors. If they want to view it locally they can.

But still it some error occurs only then we'll have to look into it.

**Comment by TanmayBhosale** [comment]
And talking about the json file, you can allow others to merge only if they were assigned an issue. Other spam prs can be closed directly. Just that everytime we'll have to check if the contributor has added his/  her name.

**Comment by Coding-Hashira** [comment]
So, what should we use? GitHub API or JSON?

**Comment by pushkaraj2007** [comment]
I think using GitHub API will be better. 

Because JSON file approach will increase our work of merging!! 

What do you think @Coding-Hashira and @TanmayBhosale ?

**Comment by Coding-Hashira** [comment]
> I think using GitHub API will be better. 
> 
> Because JSON file approach will increase our work of merging!! 
> 
> What do you think @Coding-Hashira and @TanmayBhosale ? 

I agree with you!

**Comment by pushkaraj2007** [comment]
Let's see what @TanmayBhosale thinks...

**Comment by TanmayBhosale** [comment]
Yup! I think so too. API would be a good option

**Comment by pushkaraj2007** [comment]
So do you want to work on this?

You can create it with your API secrets and keys, for now, just don't commit the .env file.

After you create a pull request I'll add my API secrets and keys to the vercel server.

**Comment by TanmayBhosale** [comment]
Yup sure I'll work on it

**Comment by pushkaraj2007** [comment]
So, I'm assigning this to you.

**Comment by TanmayBhosale** [comment]
Yup working on it!

**Comment by TanmayBhosale** [comment]
Hey, I have implemented the contributors page. Before making a pr can you just set up some env variables.
GITHUB_USER = (your user name) and GITHUB_API_KEY = (API key) which you can create [here](https://github.com/settings/tokens). For permissions, you can just check the repository permissions for now and set expiration time. For testing keep it to no expiration. To test locally add these env variables to .env.local file

**Comment by pushkaraj2007** [comment]
Added env variables, but getting some errors.

Please check PR for more info.
