### ISSUE TITLE
Remove unnecessary node packages

### ISSUE THREAD

**Issue by pushkaraj2007** [pushkaraj2007/Threadify#25]
## Problem

Currently, we are not using the 'daisyui' library but still, it is in the project which ultimately makes a large bundle and makes our site slow in production.

## Solution

Here are the steps to fix this issue:

- Fork the repository
- Clone it
- run `npm uninstall daisyui`
- commit changes
- push changes and create a PR

**Comment by E-fais** [comment]
Let me try this ;)

**Comment by pushkaraj2007** [comment]
@E-fais 

Sure, go ahead.

**Comment by selemondev** [comment]
Hello there @pushkaraj2007 👋, it has been 10 days since you assigned @E-fais to work on this issue. I would like to work on this issue, may you please assign it to me!

**Comment by pushkaraj2007** [comment]
@selemondev 

Actually @E-fais has already created PR for this issue but I'm not getting enough time to review if it's all okay or not. 

If you want can you please review it. 

Also, I've created a new issue about adding a sign up for early access page. 

If you want you can work on that issue too, it's currently open (#33).

**Comment by pushkaraj2007** [comment]
!! This issue has been resolved in #27 PR !!
