### ISSUE TITLE
[DOC] Update image in the readme file

### ISSUE THREAD

**Issue by pushkaraj2007** [pushkaraj2007/Threadify#26]
## Problem

We have decided our project logo and placed it on the website, still, the image in the readme file is not updated which has to be.

## Solution

- Head to https://threadify.vercel.app
- Take a screenshot
- Update readme.md with the screenshot you have taken
- Commit changes
- Push changes and create a pull request

**Comment by Coding-Hashira** [comment]
Can I work on this? @pushkaraj2007

**Comment by pushkaraj2007** [comment]
Sure, go ahead.

**Comment by rishabhknowss** [comment]
hey can you pls assign me the task under hacktoberfest lable?

**Comment by pushkaraj2007** [comment]
Yeah, I think @rishabhknowss is not working on this! 

So you should work on this @tmsagarofficial 

I'm going to assign you.

**Comment by tmsagarofficial** [comment]
@pushkaraj2007 Hi again, Thanks for assigning this issue to me... Will start working on it right away.

**Comment by pushkaraj2007** [comment]
!! This issue has been resolved in #28 PR !!
