### ISSUE TITLE
[FEAT] Design a logo for this project

### ISSUE THREAD

**Issue by pushkaraj2007** [pushkaraj2007/Threadify#3]
Currently, we don't have decided a logo for this project and we need one to show on the website and to create social profiles.

You can create a logo and upload it in the comments on this issue, once your designed logo gets approved, you can add your name to the contributor's section.

If you want to know what this project is exactly about, you can view [Pushkaraj Kulkarni's original tweet](https://twitter.com/pushkaraj2007/status/1577576263786835968?s=20&t=oqlRvuS0U2t83mr9kkiCiw).

Thanks for your time :)

**Comment by ArturBa** [comment]
do you have any suggestions on that logo design? 
Sth you like?

**Comment by pushkaraj2007** [comment]
@ArturBa 

Currently I don't have any design or suggestion in mind, but it has to define what project is about. 

You are totally free for your creative mind.

Do you want to work on this? Also have know what this project is about?

**Comment by ArturBa** [comment]
I've read the TT thread. It's all about some TT threads dashboard.

Please let me work on the logo desing

**Comment by pushkaraj2007** [comment]
@ArturBa 

Sure, go ahead

**Comment by ArturBa** [comment]
HI
I've created a simple logo for your platform. 
Below you'll find a png preview and a SVG 


![logo_w](https://user-images.githubusercontent.com/27014858/194768464-097b12e6-1cc5-4b46-9267-18a084c9178c.png)

![logo](https://user-images.githubusercontent.com/27014858/194768429-de038653-56e4-40f4-9cf9-f8f6a3372cfd.svg)

**Comment by KendallDoesCoding** [comment]
@pushkaraj2007 I think this should be a discussion rather then a issue.

**Comment by pushkaraj2007** [comment]
@ArturBa, It looks good 👍

Going to use it for the project 🚀

**Comment by pushkaraj2007** [comment]
@KendallDoesCoding, Yeah I agree with you on this point. 

But we didn't enable discussion tab as far now, that's why I created issue. 

BTW, if you have any design idea, let me know.

**Comment by KendallDoesCoding** [comment]
Ok cool, no worries.

**Comment by pushkaraj2007** [comment]
So @KendallDoesCoding , do you want to create a logo design?

**Comment by KendallDoesCoding** [comment]
No.. I am bad a designing creatives lol. But will try to help in the code
of this project.

**Comment by pushkaraj2007** [comment]
@KendallDoesCoding 

No worries! Looking forward to see your contributions in this project 🚀

**Comment by pushkaraj2007** [comment]
!! This issue has been resolved !!
