### ISSUE TITLE
[FEAT] Create sign up for early access page

### ISSUE THREAD

**Issue by pushkaraj2007** [pushkaraj2007/Threadify#33]
Currently we don't have any sign up for early access page or it's design. 

It'll be great if we create one for users who want to use this product. 

You are free for your creativity of designing. 

On the page there should be a form with two input fields:

- Email
- Twitter username

we just need a frontend for now, form submission API routes will be created after the frontend gets completed.

**Comment by OneAutumLeaf** [comment]
Hi @pushkaraj2007 
Can u assign this issue to me. I can create the signup page.

**Comment by pushkaraj2007** [comment]
Sure @OneAutumLeaf 

Do you have any design in mind?

**Comment by OneAutumLeaf** [comment]
No right now

**Comment by pushkaraj2007** [comment]
So @OneAutumLeaf

Can I assign this to you, will you do it?

**Comment by OneAutumLeaf** [comment]
I'm very sorry u can assign other for this work .

**Comment by pushkaraj2007** [comment]
No problem! I'll assign this to someone else

**Comment by E-fais** [comment]
I w

**Comment by E-fais** [comment]
Hey @pushkaraj2007 i would like to work on this issue. I think this project is in typescript, I am not familiar with type script. Can I create a login page with JavaScript only ??

**Comment by pushkaraj2007** [comment]
!! This issue has been resolved !!
