### ISSUE TITLE
[BUG] - Text on Early Access Page

### ISSUE THREAD

**Issue by Coding-Hashira** [pushkaraj2007/Threadify#35]
On the early access page, in mobile screens, the pointed text, needs to be centred and a little padding!

![IMG_20221115_214648.jpg](https://user-images.githubusercontent.com/96920778/201970882-429f8f5b-065f-4af6-8ee1-b6312006392b.jpg)

**Comment by pushkaraj2007** [comment]
Yeah! I think of forgot to do it! 

Do you want to work on this?

**Comment by Coding-Hashira** [comment]
Yep! 🔥🚀

**Comment by pushkaraj2007** [comment]
Go ahead 🔥
