### ISSUE TITLE
Improve the UI of dashboard page

### ISSUE THREAD

**Issue by pushkaraj2007** [pushkaraj2007/Threadify#39]
## Description

Currently, the dashboard page's UI is not much good in terms of design ( head to [Dashboard page](https://threadify.vercel.app) to get an overview )

We have to make the design look better as it is one of the crucial parts of our project

## How to:

- Head to the `pages/dashboard.tsx` file
- We are using Tailwind CSS for designing so having knowledge about it is necessary
- Now you are free for your creativity, design the page as you like

**Comment by ianishk** [comment]
I would like to work on this issue

**Comment by 0xSaksham** [comment]
@pushkaraj2007 Can I work on the issue?

**Comment by pushkaraj2007** [comment]
Do you have any design idea, @0xSaksham?

**Comment by givensuman** [comment]
@pushkaraj2007 I'd be interested in helping with this!

I'm noticing inconsistent spacing and contrast issues as a good place to start. In addition to contrast, Lighthouse has spotted some accessibility issues with `name` and `lang` tags.

**Comment by bharathkalyans** [comment]
You can add a hover effect on cards! Bit of animations will make the page interesting.

**Comment by shreyas0924** [comment]
Hey can  I work on this?

**Comment by pushkaraj2007** [comment]
@shreyas0924 

Do you have any idea of how can we improve the UI design?

**Comment by shreyas0924** [comment]
As they mentioned above, I can work on hover effect on cards and optimizing the layout for mobile devices. I think the UI looks great. It is minimalistic and good looking. We can add more subtle animations here and there to improve the UX.

**Comment by pushkaraj2007** [comment]
@shreyas0924 - Go ahead, best of luck!
