### ISSUE TITLE
Add Issue Templates

### ISSUE THREAD

**Issue by Coding-Hashira** [pushkaraj2007/Threadify#4]
As of now, this repository doesn't have any issue templates, which makes issues quite inconsistent. It would be better to add some common issue templates (Such as bug, feature, enhancement, docs)

Also, if someone else wants to work on this issue, I'm completely fine with that!

**Comment by atharvai812** [comment]
assign me

**Comment by pushkaraj2007** [comment]
@atharvai812

Sure, Go ahead.

**Comment by pushkaraj2007** [comment]
Hey @atharvai812, are you working on this issue or should I assign this to someone else?

**Comment by vaibhavmishra4g** [comment]
yup i read the docs on github how to do it

**Comment by vaibhavmishra4g** [comment]
i'll add the standard templates for the mentioned tasks

**Comment by pushkaraj2007** [comment]
@vaibhavmishra4g 

Then sure, go ahead.

**Comment by vaibhavmishra4g** [comment]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository this is the link i'll follow

**Comment by pushkaraj2007** [comment]
Great, I'm assigning you this issue. 

Happy contributing :)
