### ISSUE TITLE
Update of social links to enable opening in new tabs

### ISSUE THREAD

**Issue by tmsagarofficial** [pushkaraj2007/Threadify#43]
**Describe the bug**
All the social links at the bottom of the page open in the same tab as the current tab.
Changing this to open in new tab will make its use more comfortable to users as they don't hav to go to previous tab for every social logo .

**To Reproduce**
1. Go to https://threadify.vercel.app/
2. Scroll down to see the social logos( github and twitter)
3. Click on twitter or github logo.
4. See that whatever social logo is clicked that link is opened in the same tab as the current tab

**Expected behavior**
I would like this to be able to open each social link in a new tab for ese of use and access of the threadify after use of social links

**Screenshots**
`See that these links open in the same tab`

<img width="917" alt="image" src="https://user-images.githubusercontent.com/110724849/223539661-f8805e15-2f63-46f1-bd63-dd916cc8baec.png">

<img width="917" alt="image" src="https://user-images.githubusercontent.com/110724849/223539586-d78a10ec-1d07-417e-80af-d7e5cc48f8f7.png">

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser: OPera
 - Version: LVL4 (core: 95.0.4635.74)

**Comment by seinlusnyongesa** [comment]
hello @tmsagarofficial I read through the description of the bug. can i work on it ?

**Comment by tmsagarofficial** [comment]
Hey, @seinlusnyongesa it's like I'm not the admin and hence I can't assign or do anything like that. I'm also waiting for long a time for my issue so that I can work on it once @pushkaraj2007 assigns 😅

**Comment by seinlusnyongesa** [comment]
okay, thanks for the response man, good luck.

**Comment by pushkaraj2007** [comment]
@tmsagarofficial, do you want to work on this?

**Comment by tmsagarofficial** [comment]
> @tmsagarofficial, do you want to work on this?

Yeah

**Comment by tmsagarofficial** [comment]
> I was quite busy with my academics, so I was unable check the issue and assign.
> 
> I have assigned @tmsagarofficial now, so you can start working on this issue now.

Thanks mate . I will start working on this 🚀

**Comment by tmsagarofficial** [comment]
check @pushkaraj2007
