### ISSUE TITLE
.env not mentioned for contribution.

### ISSUE THREAD

**Issue by Sanchitbajaj02** [pushkaraj2007/Threadify#48]
Hi 👋 
While looking to contribute to the repository, I found out that in Contribution Guidelines, there is no mention of any type of environment variables a contributor needs to set up before contribution.

I think I might be able to maintain that into the documentation so please assign me this issue.
Thank you

**Comment by pushkaraj2007** [comment]
Sure, go ahead.

**Comment by Sanchitbajaj02** [comment]
@pushkaraj2007 please review and merge my PR #50
