### ISSUE TITLE
Error while Getting started 

### ISSUE THREAD

**Issue by mohitmohlia** [pushkaraj2007/Threadify#49]
**Describe the bug**
Not able to Get started with twitter

**To Reproduce**
1. Visit https://threadify.vercel.app/
2. Click on Get started
3. It redirects to the twitter page
4. error : Something went wrong

**Expected behavior**
Should be able to login

**Screenshots**

https://user-images.githubusercontent.com/46368810/230705571-4a4b2a80-be6b-4426-88d5-0b266476c5bd.mov

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser : Chrome

**Comment by Sanchitbajaj02** [comment]
Yeah, I faced they same issue, even with my local machine. Looking for the problem as well.

**Comment by pushkaraj2007** [comment]
Actually, previously there was a Twitter login screen, but because of the increase in the price of Twitter API, we cannot continue using it.

I'm thinking of implementing email login or other Signin providers like Google. 

What are your thoughts on this?

**Comment by mohitmohlia** [comment]
what about login via github?

**Comment by pushkaraj2007** [comment]
@mohitmohlia 

That will work too, we can also add login via Google.
