### ISSUE TITLE
No contributors listed on Contributors page

### ISSUE THREAD

**Issue by KendallDoesCoding** [pushkaraj2007/Threadify#52]
**Describe the bug**
No contributors are listed on the contributors page.

**To Reproduce**
1. Go to "Website".
2. Go to 'Contributors Page.'

**Expected behavior**
Contributors are supposed to show?

**Screenshots**
![image](https://user-images.githubusercontent.com/84712013/234781627-4147ad04-86aa-4c0e-9777-117fcfb25463.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by pushkaraj2007** [comment]
Thanks for raising this issue!

@KendallDoesCoding, Do you want to work on this?

**Comment by KendallDoesCoding** [comment]
> Thanks for raising this issue!
> 
> @KendallDoesCoding, Do you want to work on this?

I'm not too good at Typescript, so no sorry.

**Comment by pushkaraj2007** [comment]
@KendallDoesCoding 

No worries, I'll look forward to solving this issue
