### ISSUE TITLE
Add Code of Conduct and Pull Request Template

### ISSUE THREAD

**Issue by theritikchoure** [pushkaraj2007/Threadify#60]
A code of conduct is a document that outlines expectations for behavior and interaction within a community or project, while a pull request template is a standardized format for submitting proposed changes to the project.

Having a code of conduct helps establish a welcoming and inclusive environment, where all participants are treated with respect and dignity. It can also provide a framework for resolving conflicts and addressing issues that may arise during the development process.

A pull request template, on the other hand, streamlines the process of submitting changes to a project by providing a consistent format for contributors to follow. This can include details such as the purpose of the proposed changes, any relevant links or resources, and instructions for testing and reviewing the changes.

**Comment by pushkaraj2007** [comment]
Thanks for opening this issue, Ritik!

You are right having a Code of Conduct and PR template is necessary, do you want to work on this?

If yes, make sure to make separate PRs for each.

**Comment by theritikchoure** [comment]
Ok i will make separate PRs
